# 后端服务配置
server:
  port: 3000

# jwt的配置
jwt:
  secret: 'xxx' # jwt私钥
  signOptions:
    expiresIn: '12h' # jwt过期时间

# 数据库配置
db:
  type: "mysql" # "mysql" | "mariadb"
  host: "127.0.0.1"
  port: 3306
  username: "xxx"
  password: "xxx"
  database: "wife_kitchen"
  autoLoadEntities: true
  synchronize: false # 生产环境禁止打开
  logging: true # 打开sql日志

# redis的配置
redis:
  config:
    host: '127.0.0.1'
    port: 6379
    # password: 'xxxx'

# swagger的配置
swagger:
  open: true # 是否开启
  path: "swagger-docs" # 文档路径
  title: "领悟服务端api文档" # swagger标题
  description: "领悟服务端（pc）" # swagger描述
  version: "1.0.0" # 接口版本
  bearerAuth: # 认证配置
    type: "http"
    in: "header"
    name: "Authorization"
